export const SEARCH_MOVIE_START = 'SEARCH_MOVIE_START';
export const SEARCH_MOVIE_ERROR = 'SEARCH_MOVIE_ERROR';
export const SEARCH_MOVIE_COMPLETE = 'SEARCH_MOVIE_COMPLETE';

export const SEARCH_MOVIE_BY_START = 'SEARCH_MOVIE_BY_START'
export const SEARCH_MOVIE_BY_ERROR = 'SEARCH_MOVIE_BY_ERROR'
export const SEARCH_MOVIE_BY_COMPLETE = 'SEARCH_MOVIE_BY_COMPLETE'
